# Relative paths work OK as long as you start the tool from its local dir
template_path: .

# This folder gets copied into the output directory
template_static_path: ../assets

# Templates should have filenames starting in template-
default_template: template-doc.html
pdf_template: template-forpdf.html

# HTML, PDF, GFM all get output here
out_path: ..

# MD files should be here (and in subdirs)
content_path: ../content

# This folder gets copied into the output directory
content_static_path: ../img

# PDF creation needs a dir for temporary files
temporary_files_path: /tmp/

prince_executable: prince

targets:
    # First member is the default that gets built when target not specified
    -   name: local
        multicode_tabs: true
    -   name: ripple.com
        multicode_tabs: true
    -   name: pdf
        multicode_tabs: false

pages:
    -   name: Overview
        html: index.html
        sidebar: false
        template: template-index.html

    -   name: Paths
        category: Concepts
        html: paths.html
        md: paths.md
        ripple.com: https://ripple.com/build/paths/
        sidebar: category-toc

    -   name: Fees (Disambiguation)
        category: Concepts
        html: fees.html
        md: fees.md
        ripple.com: https://ripple.com/knowledge_center/fees-disambiguation/
        sidebar: category-toc

    -   name: Transfer Fees
        category: Concepts
        html: transfer_fees.html
        md: transferrate.md
        ripple.com: https://ripple.com/knowledge_center/transfer-fees/
        sidebar: category-toc

    -   name: Transaction Cost
        category: Concepts
        html: tx-cost.html
        md: tx-cost.md
        ripple.com: https://ripple.com/build/transaction-cost/
        sidebar: category-toc

    -   category: Concepts
        html: fee-voting.html
        md: fee-voting.md
        name: Fee Voting
        ripple.com: https://ripple.com/build/fee-voting/
        sidebar: category-toc

    -   category: Concepts
        html: reserves.html
        md: reserves.md
        name: Reserves
        ripple.com: https://ripple.com/build/reserves/
        sidebar: category-toc

    -   category: Concepts
        html: freeze.html
        md: freeze.md
        name: Freeze
        ripple.com: https://ripple.com/build/freeze/
        sidebar: category-toc

    -   category: Tutorials
        html: rippleapi_quickstart.html
        md: rippleapi_quickstart.md
        name: RippleAPI Quick Start Guide
        sidebar: page-toc

    -   category: References
        html: rippled-apis.html
        md: rippled.md
        name: rippled
        ripple.com: https://ripple.com/build/rippled-apis/
        sidebar: page-toc

    -   category: Tutorials
        html: rippled-setup.html
        md: rippled-setup.md
        name: rippled Setup
        ripple.com: https://ripple.com/build/rippled-setup/
        sidebar: page-toc

    -   category: References
        html: transactions.html
        md: tx_format.md
        name: Transactions
        ripple.com: https://ripple.com/build/transactions/
        sidebar: page-toc

    -   category: References
        html: ripple-ledger.html
        md: ledger_format.md
        name: Ledger Format
        ripple.com: https://ripple.com/build/ledger-format/
        sidebar: page-toc

    -   category: Tutorials
        html: reliable_tx.html
        md: reliable_tx.md
        name: Reliable Transaction Submission
        ripple.com: https://ripple.com/build/reliable-transaction-submission/
        sidebar: page-toc

    -   category: Tutorials
        html: gateway_guide.html
        md: gateway_guide.md
        name: Gateway Guide
        ripple.com: https://ripple.com/build/gateway-guide/
        sidebar: page-toc

    -   category: References
        html: data_api_v2.html
        md: data_v2.md
        name: Ripple Data API v2
        ripple.com: https://ripple.com/build/data-api-v2/
        sidebar: page-toc

    -   category: References
        html: rippleapi.html
        md: https://raw.githubusercontent.com/ripple/ripple-lib/0.16.7/docs/index.md
        name: RippleAPI
        ripple.com: https://ripple.com/build/rippleapi/
        sidebar: page-toc

    -   category: API Tools
        html: ripple-api-tool.html
        name: WebSocket API Tool
        ripple.com: https://ripple.com/build/websocket-tool/
        sidebar: custom
        targets:
        - local
        - ripple.com
        template: template-ripple-api-tool.html

    -   category: API Tools
        html: data-api-v2-tool.html
        methods_js: js/apitool-methods-data_v2.js
        name: Data API v2 Tool
        rest_host: https://data.ripple.com
        sidebar: custom
        targets:
        - local
        - ripple.com
        template: template-rest-api-tool.html
